import logging
from datetime import datetime, timedelta


# Выбор инструмента
tickers = [
        'BTCUSDT',
        'ETHUSDT',
        'GFTUSDT',
        'CREAMUSDT',
        'XRPUSDT',
        'HIFIUSDT',
        'LINKUSDT',
        'LOOMUSDT',
        'BLZUSDT',
        'SHIBUSDT',
        'WLDUSDT',
        'FLMUSDT',
        'BNBUSDT',
        'FDUSDUSDT',
        'KNCUSDT',
        'FRONTUSDT',
        'SOLUSDT',
        'LTCUSDT',
        'SNXUSDT',
        'STPTUSDT',
        'FTTUSDT',
        'PNTUSDT',
        'SUIUSDT',
        'CYBERUSDT',
        'DOGEUSDT',
        'ARBUSDT',
        'TUSDUSDT',
        'CRVUSDT',
        'PEPEUSDT',
        'APTUSDT',
        'STMXUSDT',
        'TRXUSDT',
        'OOKIUSDT',
        'LUNAUSDT',
        'SXPUSDT',
        'BCHUSDT',
        'EURUSDT',
        'AXSUSDT',
        'MATICUSDT',
        'ALCXUSDT',
        'RUNEUSDT',
        'WTCUSDT',
        'TRBUSDT',
        'MTLUSDT',
        'FISUSDT',
        'AVAXUSDT',
        'ARKUSDT',
        'OPUSDT',
        'LEVERUSDT',
        'LINAUSDT',
        'PHBUSDT',
        'AUCTIONUSDT',
        'IMXUSDT',
        'DATAUSDT',
        'IQUSDT',
        'MULTIUSDT',
        'FILUSDT',
        'THETAUSDT',
        'LUNCUSDT',
        'ADAUSDT',
        'WINGUSDT',
        'ANKRUSDT',
        'APEUSDT',
        'ANTUSDT',
        'XMRUSDT',
        'HOOKUSDT',
        'PERLUSDT',
        'DOTUSDT',
        'REIUSDT',
        'SEIUSDT',
        'HBARUSDT',
        'MASKUSDT',
        'GMTUSDT',
        'GALAUSDT',
        'MANAUSDT',
        'STORJUSDT',
        'MCUSDT',
        'AKROUSDT',
        'YGGUSDT',
        'TOMOUSDT',
        'FETUSDT',
        'MKRUSDT',
        'INJUSDT',
        'OAXUSDT',
        'ACHUSDT',
        'FIDAUSDT',
        'CFXUSDT',
        'SANDUSDT',
        'JASMYUSDT',
        'RNDRUSDT',
        'BAKEUSDT',
        'IDUSDT',
        'ATOMUSDT',
        'DYDXUSDT',
        'ALGOUSDT',
        'ELFUSDT',
        'SPELLUSDT',
        'UNFIUSDT',
        'RDNTUSDT',
        'AAVEUSDT',
        'COMPUSDT',
        'NEARUSDT',
        'EOSUSDT',
        'FTMUSDT',
        'ETCUSDT',
        'XVSUSDT',
        'AMBUSDT',
        'KMDUSDT',
        'MAGICUSDT',
        'PERPUSDT',
        'GRTUSDT',
        'KAVAUSDT',
        # 'MBOXUSDT',
        # 'ZILUSDT',
        # 'SUSHIUSDT',
        # 'UNIUSDT',
        # 'XLMUSDT',
        # 'RPLUSDT',
        # 'CELOUSDT',
        # 'VETUSDT',
        # 'WAVESUSDT',
        # 'LRCUSDT',
        # 'WOOUSDT',
        # 'AGLDUSDT',
        # 'STGUSDT',
        # 'AGIXUSDT',
        # 'XECUSDT',
        # 'MOVRUSDT',
        # 'OGNUSDT',
        # 'DREPUSDT',
        # 'REEFUSDT',
        # 'STXUSDT',
        # 'IDEXUSDT',
        # 'ENJUSDT',
        # 'LPTUSDT',
        # 'QUICKUSDT',
        # 'MAVUSDT',
        # 'ARKMUSDT',
        # 'HIGHUSDT',
        # 'ICPUSDT',
        # 'OGUSDT',
        # 'CELRUSDT',
        # 'FORTHUSDT',
        # 'GLMRUSDT',
        # 'BELUSDT',
        # 'ONEUSDT',
        # 'YFIIUSDT',
        # 'ACAUSDT',
        # 'CHZUSDT',
        # 'LDOUSDT',
        # 'COMBOUSDT',
        # 'KLAYUSDT',
        # 'KEYUSDT',
        # 'ASTRUSDT',
        # 'LITUSDT',
        # 'ROSEUSDT',
        # 'QNTUSDT',
        # 'MDTUSDT',
        # 'EGLDUSDT',
        # 'EPXUSDT',
        # 'TRUUSDT',
        # 'SFPUSDT',
        # 'AMPUSDT',
        # 'C98USDT',
        # 'ONTUSDT',
        # 'GALUSDT',
        # 'PEOPLEUSDT',
        # 'MINAUSDT',
        # 'VIDTUSDT',
        # 'FLOWUSDT',
        # 'WRXUSDT',
        # 'ZRXUSDT',
        # 'NEOUSDT',
        # 'CAKEUSDT',
        # 'TUSDT',
        # 'LQTYUSDT',
        # 'EDUUSDT',
        # 'ENSUSDT',
        # 'OMUSDT',
        # 'FXSUSDT',
        # 'SSVUSDT',
        # 'DOCKUSDT',
        # 'OXTUSDT',
        # 'UMAUSDT',
        # 'BURGERUSDT',
        # 'SLPUSDT',
        # 'CHRUSDT',
        # 'CLVUSDT',
        # 'DARUSDT',
        # 'GMXUSDT',
        # 'BNTUSDT',
        # 'ADADOWNUSDT',
        # 'ATAUSDT',
        # 'DFUSDT',
        # 'DASHUSDT',
        # 'PENDLEUSDT',
        # 'XVGUSDT',
        # 'CITYUSDT',
        # 'QKCUSDT',
        # 'JOEUSDT',
        # 'IOTAUSDT',
        # '1INCHUSDT',
        # 'FLOKIUSDT',
]
timeframes = ['30MINUTE']

# Получаем текущую дату и время
current_datetime = datetime.now()
# Получаем только дату (без времени)
current_date = current_datetime.date()

# Плюсуем один день
s_date = str(current_date - timedelta(days=7))+' 00:00:00'
u_date = str(current_date + timedelta(days=1))+' 00:00:00'

# Комиссия Binance 0,2%
commission = 0.2

# Совместить таблицы Excel
combined_results = False

# Ключи Binance
api_key = 'juCgjiYf8mj8V0NJE3nePaU70IXAvjgSMaK7JkpOC0UsZfS3WGAdNEpcrIaWIBRK'
api_secret = 'fQLPCg3dVy8y2SQQAHUSCSOhN94BzlyZOMY2dDfahevcPfU5foFyasy4TfHEHe9N'

# Ключи Telegram
token = "6048284555:AAHP2qXwhOEpVSiMOWtLGJ_eUlYVirpnDVc"
chat_id = "@bot_torgyet"
url_base = f"https://api.telegram.org/bot{token}/"
url_message = f"https://api.telegram.org/bot{token}/sendMessage"
url_image = f"https://api.telegram.org/bot{token}/sendPhoto"

# Уровень логирования
LOGGING_LEVEL = logging.INFO

# Количество потоков
CPU_COUNT = 10

# Папки для хранения bigdata, результатов и графиков
RESULTS_DIR = './data/results/'
IMAGES_DIR = './data/images/'
BIGDATA_DIR = './data/bigdata/'

UTILS_DIR = './utils/'
TELEGRAM_DIR = './utils/telegram/'
