import logging

from openpyxl.utils import get_column_letter
from openpyxl.workbook import Workbook

import config


class ExcelSaver:
    """Обработчик сохранения Excel файлов."""

    def __init__(
        self,
        ticker,
        direction,
        timeframe_interval,
        s_date,
        u_date,
        all_other_parameters
    ) -> None:
        self.ticker = ticker
        self.direction = direction
        self.timeframe_interval = timeframe_interval
        self.s_date = s_date
        self.u_date = u_date
        self.all_other_parameters = all_other_parameters

    def get_file_path(self):
        """Получение пути сохраняемого файла."""
        file_name = (
            f'{self.direction}_{self.ticker}_{self.timeframe_interval}_'
            f'{self.s_date[:10]}_{self.u_date[:10]}.xlsx'
        )
        return config.RESULTS_DIR + file_name

    @staticmethod
    def adjust_column_width(sheet):
        """
        Автоматически задаем ширину столбцов таблицы Excel
        """
        for col in sheet.columns:
            max_length = 0
            column = col[0].column_letter
            for cell in col:
                try:
                    if len(str(cell.value)) > max_length:
                        max_length = len(str(cell.value))
                except Exception as ex:
                    logging.error(ex)
            adjusted_width = (max_length + 2)
            sheet.column_dimensions[column].width = adjusted_width

    def write_to_excel(self, file_path):
        """Сохранение Excel файла."""
        headers = [
            'Дата',
            'ticker',
            'open_to_close_trade_duration',

            'Вход',
            'Стоп',
            'Тейк',
            'Результат',
            'Разница',
            'Успешно',
            'Stop',
            'Take',
            'diff_price_change',

            'percentage_difference_min_low_and_t1',
            'percentage_difference_min_close_and_t1',
            'percentage_difference_max_close_and_t1',

            'std_dev_y_mean_y',
            'std_dev_y_mean_y_1',
            'std_dev_y_mean_y_2',
            'std_dev_y_mean_y_3',
            'std_dev_y_mean_y_4',
            'std_dev_y_mean_y_5',
            'std_dev_y_mean_y_6',
            'std_dev_y_mean_y_7',
            'std_dev_y_t2_t3_up_enter',

            'tail_to_body_ratio_t1up',
            'tail_to_body_ratio_t2',
            'tail_to_body_ratio_t3',
            'tail_to_body_ratio_enter_point_back_1',

            'area_under_curve',
            'radius_curvature_t2_t3_up_enter',
            'angle_t2_t3',
            'angle_t3_up_enter',
            'angle_deg_LT',
            'max_distance',
            'length3_point_t1_t2_norm',

            'rsi_value1',
            'rsi_value2',
            'rsi_value3',
            'rsi_value_enter',

            'vwap_t1_v2',
            'vwap_enter_v2',
            'vwap_ratio_t1_v2',
            'vwap_ratio_enter_v2',

            'vwap_ratio_t1',
            'vwap_ratio_enter',

            'model_interval',

            'ratio1_golden',
            'ratio2_golden',
            'ratio1_ratio2',
            'ratio2_ratio1',
            'CP_to_t1up',

            'num_of_distances_low_to_t1up',
            'num_of_distances_high_to_t4up',
            'mse_t1_t2',
            'mse_t2_t3',
            'mse_t3_t4',
            'mse_t1_t3',
            'mse',

            # 'XE_to_CB',
            # 'XA_to_AC',
            # 'XA_to_CE',
            # 'XE_to_XF',
            # 'XD_to_XB',
            # 'XB_to_XE',
            # 'XB_to_XA',
            # 'AB_to_BC',
            # 'AD_to_AB',
            # 'AC_to_BD',
            # 'AC_to_CE',
            # 'AF_to_FC',
            # 'AF_to_CE',
            # 'AE_to_FC',
            # 'BF_to_DF',
            # 'BF_to_BC',
            # 'AB_to_BF',
            # 'BC_to_BD',
            # 'AB_to_XA',
            # 'BC_to_AB',
            # 'CD_to_BC',
            'parallel',

            # 'entry_above_l0',
            # 'entry_above_lc1_line',
            #
            # 'ratio_num_high_above_lc1_to_all',
            # 'ratio_num_low_below_lt1_to_all',
            # 'ratio_num_close_above_lc1_to_all',
            # 'ratio_num_close_below_lt1_to_all',
            # 'ratio_high_low_fan',
            # 'ratio_close_fan',
            # 'ratio_sum_fan',
            # 'ratio_medium_to_lower',
            # 'ratio_medium_to_upper',
            # 'ratio_medium_to_lateral',
            # 'ratio_medium_to_all',
            #
            # 'angle_lt_lt1',
            # 'angle_lc_lc1',
            # 'angle_lt1_lc1',

            # 'aq_ratio_t1_t4_to_t1_t3',
            # 'aq_ratio_t3_t4_to_t1_t3',
            # 'aq_free_area',
            # 'angle_t3_t4_t4_t3',
            # 'aspect_ratio_t1_t4',
            # 'aspect_ratio_t1_t3',
            # 'height_ratio_t1_t2_to_t1_t4',
            # 'width_ratio_t3_t4_to_t3_t4',
            # 'width_ratio_t1_t2_to_t3_t4',
            # 'width_ratio_t1_t2_to_t2_t4',
            # 'width_ratio_t1_t2_to_t2_t3',
            # 'width_t1_t2_t3_t4',
            # 'width_t2_t3_t4',
            # 'width_CP_t1',
            # 'width_CP_t1_to_t1_t3',
            # 'width_t1_t3_to_t3_t4',
            # 'height_ratio_t1_t2_to_t2_t4',

            # 'dist_cp_norm_t1_norm',
            # 'dist_cp_norm_t2_norm',
            # 'dist_cp_norm_t3_norm',
            # 'dist_cp_norm_t4_norm',
            # 'dist_cp_norm_t5_norm',
            # 'dist_cp_norm_entry_point_norm',
            # 'dist_cp_norm_at_1_norm',
            # 'dist_cp_norm_at_2_norm',
            # 'dist_cp_norm_at_2_lc_norm',
            # 'dist_cp_norm_at_3_norm',
            # 'dist_cp_norm_at_4_norm',
            # 'dist_cp_norm_at_5_norm',
            # 'dist_cp_norm_at_5_lc_norm',
            # 'dist_cp_norm_at_6_norm',
            # 'dist_cp_norm_at_6_lc_norm',
            # 'dist_cp_norm_enter_cp_norm',
            # 'dist_cp_norm_cp_enter_norm',
            # 'dist_cp_norm_t4_cp_norm',
            # 'dist_cp_norm_t3_cp_norm',
            # 'dist_cp_norm_t2_cp_norm',
            # 'dist_cp_norm_t1_cp_norm',
            # 'dist_cp_norm_above_t1_t2_norm',
            # 'dist_cp_norm_below_t1_t2_norm',
            # 'dist_cp_norm_above_t2_t3_norm',
            # 'dist_cp_norm_below_t2_t3_norm',
            # 'dist_cp_norm_above_t3_t4_norm',
            # 'dist_cp_norm_below_t3_t4_norm',
            # 'dist_cp_norm_above_t4_t5_norm',
            # 'dist_cp_norm_below_t4_t5_norm',
            # 'dist_cp_norm_above_t5_entry_norm',
            # 'dist_cp_norm_below_t5_entry_norm',
            # 'dist_cp_norm_above_t2_t5_norm',
            # 'dist_cp_norm_below_t2_t5_norm',
            # 'dist_cp_norm_above_t3_entry_norm',
            # 'dist_cp_norm_below_t3_entry_norm',
            # 'dist_cp_norm_above_t1_entry_norm',
            # 'dist_cp_norm_below_t1_entry_norm',
            # 'dist_cp_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_cp_norm_take100_point_norm',
            # 'dist_cp_norm_mid_dist_t2_t5_norm',
            # 'dist_cp_norm_mid_dist_t5_entry_norm',
            # 'dist_cp_norm_mid_dist_t1_entry_norm',
            # 'dist_t1_norm_t2_norm',
            # 'dist_t1_norm_t3_norm',
            # 'dist_t1_norm_t4_norm',
            # 'dist_t1_norm_t5_norm',
            # 'dist_t1_norm_entry_point_norm',
            # 'dist_t1_norm_at_1_norm',
            # 'dist_t1_norm_at_2_norm',
            # 'dist_t1_norm_at_2_lc_norm',
            # 'dist_t1_norm_at_3_norm',
            # 'dist_t1_norm_at_4_norm',
            # 'dist_t1_norm_at_5_norm',
            # 'dist_t1_norm_at_5_lc_norm',
            # 'dist_t1_norm_at_6_norm',
            # 'dist_t1_norm_at_6_lc_norm',
            # 'dist_t1_norm_enter_cp_norm',
            # 'dist_t1_norm_cp_enter_norm',
            # 'dist_t1_norm_t4_cp_norm',
            # 'dist_t1_norm_t3_cp_norm',
            # 'dist_t1_norm_t2_cp_norm',
            # 'dist_t1_norm_t1_cp_norm',
            # 'dist_t1_norm_above_t1_t2_norm',
            # 'dist_t1_norm_below_t1_t2_norm',
            # 'dist_t1_norm_above_t2_t3_norm',
            # 'dist_t1_norm_below_t2_t3_norm',
            # 'dist_t1_norm_above_t3_t4_norm',
            # 'dist_t1_norm_below_t3_t4_norm',
            # 'dist_t1_norm_above_t4_t5_norm',
            # 'dist_t1_norm_below_t4_t5_norm',
            # 'dist_t1_norm_above_t5_entry_norm',
            # 'dist_t1_norm_below_t5_entry_norm',
            # 'dist_t1_norm_above_t2_t5_norm',
            # 'dist_t1_norm_below_t2_t5_norm',
            # 'dist_t1_norm_above_t3_entry_norm',
            # 'dist_t1_norm_below_t3_entry_norm',
            # 'dist_t1_norm_above_t1_entry_norm',
            # 'dist_t1_norm_below_t1_entry_norm',
            # 'dist_t1_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_t1_norm_take100_point_norm',
            # 'dist_t1_norm_mid_dist_t2_t5_norm',
            # 'dist_t1_norm_mid_dist_t5_entry_norm',
            # 'dist_t1_norm_mid_dist_t1_entry_norm',
            # 'dist_t2_norm_t3_norm',
            # 'dist_t2_norm_t4_norm',
            # 'dist_t2_norm_t5_norm',
            # 'dist_t2_norm_entry_point_norm',
            # 'dist_t2_norm_at_1_norm',
            # 'dist_t2_norm_at_2_norm',
            # 'dist_t2_norm_at_2_lc_norm',
            # 'dist_t2_norm_at_3_norm',
            # 'dist_t2_norm_at_4_norm',
            # 'dist_t2_norm_at_5_norm',
            # 'dist_t2_norm_at_5_lc_norm',
            # 'dist_t2_norm_at_6_norm',
            # 'dist_t2_norm_at_6_lc_norm',
            # 'dist_t2_norm_enter_cp_norm',
            # 'dist_t2_norm_cp_enter_norm',
            # 'dist_t2_norm_t4_cp_norm',
            # 'dist_t2_norm_t3_cp_norm',
            # 'dist_t2_norm_t2_cp_norm',
            # 'dist_t2_norm_t1_cp_norm',
            # 'dist_t2_norm_above_t1_t2_norm',
            # 'dist_t2_norm_below_t1_t2_norm',
            # 'dist_t2_norm_above_t2_t3_norm',
            # 'dist_t2_norm_below_t2_t3_norm',
            # 'dist_t2_norm_above_t3_t4_norm',
            # 'dist_t2_norm_below_t3_t4_norm',
            # 'dist_t2_norm_above_t4_t5_norm',
            # 'dist_t2_norm_below_t4_t5_norm',
            # 'dist_t2_norm_above_t5_entry_norm',
            # 'dist_t2_norm_below_t5_entry_norm',
            # 'dist_t2_norm_above_t2_t5_norm',
            # 'dist_t2_norm_below_t2_t5_norm',
            # 'dist_t2_norm_above_t3_entry_norm',
            # 'dist_t2_norm_below_t3_entry_norm',
            # 'dist_t2_norm_above_t1_entry_norm',
            # 'dist_t2_norm_below_t1_entry_norm',
            # 'dist_t2_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_t2_norm_take100_point_norm',
            # 'dist_t2_norm_mid_dist_t2_t5_norm',
            # 'dist_t2_norm_mid_dist_t5_entry_norm',
            # 'dist_t2_norm_mid_dist_t1_entry_norm',
            # 'dist_t3_norm_t4_norm',
            # 'dist_t3_norm_t5_norm',
            # 'dist_t3_norm_entry_point_norm',
            # 'dist_t3_norm_at_1_norm',
            # 'dist_t3_norm_at_2_norm',
            # 'dist_t3_norm_at_2_lc_norm',
            # 'dist_t3_norm_at_3_norm',
            # 'dist_t3_norm_at_4_norm',
            # 'dist_t3_norm_at_5_norm',
            # 'dist_t3_norm_at_5_lc_norm',
            # 'dist_t3_norm_at_6_norm',
            # 'dist_t3_norm_at_6_lc_norm',
            # 'dist_t3_norm_enter_cp_norm',
            # 'dist_t3_norm_cp_enter_norm',
            # 'dist_t3_norm_t4_cp_norm',
            # 'dist_t3_norm_t3_cp_norm',
            # 'dist_t3_norm_t2_cp_norm',
            # 'dist_t3_norm_t1_cp_norm',
            # 'dist_t3_norm_above_t1_t2_norm',
            # 'dist_t3_norm_below_t1_t2_norm',
            # 'dist_t3_norm_above_t2_t3_norm',
            # 'dist_t3_norm_below_t2_t3_norm',
            # 'dist_t3_norm_above_t3_t4_norm',
            # 'dist_t3_norm_below_t3_t4_norm',
            # 'dist_t3_norm_above_t4_t5_norm',
            # 'dist_t3_norm_below_t4_t5_norm',
            # 'dist_t3_norm_above_t5_entry_norm',
            # 'dist_t3_norm_below_t5_entry_norm',
            # 'dist_t3_norm_above_t2_t5_norm',
            # 'dist_t3_norm_below_t2_t5_norm',
            # 'dist_t3_norm_above_t3_entry_norm',
            # 'dist_t3_norm_below_t3_entry_norm',
            # 'dist_t3_norm_above_t1_entry_norm',
            # 'dist_t3_norm_below_t1_entry_norm',
            # 'dist_t3_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_t3_norm_take100_point_norm',
            # 'dist_t3_norm_mid_dist_t2_t5_norm',
            # 'dist_t3_norm_mid_dist_t5_entry_norm',
            # 'dist_t3_norm_mid_dist_t1_entry_norm',
            # 'dist_t4_norm_t5_norm',
            # 'dist_t4_norm_entry_point_norm',
            # 'dist_t4_norm_at_1_norm',
            # 'dist_t4_norm_at_2_norm',
            # 'dist_t4_norm_at_2_lc_norm',
            # 'dist_t4_norm_at_3_norm',
            # 'dist_t4_norm_at_4_norm',
            # 'dist_t4_norm_at_5_norm',
            # 'dist_t4_norm_at_5_lc_norm',
            # 'dist_t4_norm_at_6_norm',
            # 'dist_t4_norm_at_6_lc_norm',
            # 'dist_t4_norm_enter_cp_norm',
            # 'dist_t4_norm_cp_enter_norm',
            # 'dist_t4_norm_t4_cp_norm',
            # 'dist_t4_norm_t3_cp_norm',
            # 'dist_t4_norm_t2_cp_norm',
            # 'dist_t4_norm_t1_cp_norm',
            # 'dist_t4_norm_above_t1_t2_norm',
            # 'dist_t4_norm_below_t1_t2_norm',
            # 'dist_t4_norm_above_t2_t3_norm',
            # 'dist_t4_norm_below_t2_t3_norm',
            # 'dist_t4_norm_above_t3_t4_norm',
            # 'dist_t4_norm_below_t3_t4_norm',
            # 'dist_t4_norm_above_t4_t5_norm',
            # 'dist_t4_norm_below_t4_t5_norm',
            # 'dist_t4_norm_above_t5_entry_norm',
            # 'dist_t4_norm_below_t5_entry_norm',
            # 'dist_t4_norm_above_t2_t5_norm',
            # 'dist_t4_norm_below_t2_t5_norm',
            # 'dist_t4_norm_above_t3_entry_norm',
            # 'dist_t4_norm_below_t3_entry_norm',
            # 'dist_t4_norm_above_t1_entry_norm',
            # 'dist_t4_norm_below_t1_entry_norm',
            # 'dist_t4_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_t4_norm_take100_point_norm',
            # 'dist_t4_norm_mid_dist_t2_t5_norm',
            # 'dist_t4_norm_mid_dist_t5_entry_norm',
            # 'dist_t4_norm_mid_dist_t1_entry_norm',
            # 'dist_t5_norm_entry_point_norm',
            # 'dist_t5_norm_at_1_norm',
            # 'dist_t5_norm_at_2_norm',
            # 'dist_t5_norm_at_2_lc_norm',
            # 'dist_t5_norm_at_3_norm',
            # 'dist_t5_norm_at_4_norm',
            # 'dist_t5_norm_at_5_norm',
            # 'dist_t5_norm_at_5_lc_norm',
            # 'dist_t5_norm_at_6_norm',
            # 'dist_t5_norm_at_6_lc_norm',
            # 'dist_t5_norm_enter_cp_norm',
            # 'dist_t5_norm_cp_enter_norm',
            # 'dist_t5_norm_t4_cp_norm',
            # 'dist_t5_norm_t3_cp_norm',
            # 'dist_t5_norm_t2_cp_norm',
            # 'dist_t5_norm_t1_cp_norm',
            # 'dist_t5_norm_above_t1_t2_norm',
            # 'dist_t5_norm_below_t1_t2_norm',
            # 'dist_t5_norm_above_t2_t3_norm',
            # 'dist_t5_norm_below_t2_t3_norm',
            # 'dist_t5_norm_above_t3_t4_norm',
            # 'dist_t5_norm_below_t3_t4_norm',
            # 'dist_t5_norm_above_t4_t5_norm',
            # 'dist_t5_norm_below_t4_t5_norm',
            # 'dist_t5_norm_above_t5_entry_norm',
            # 'dist_t5_norm_below_t5_entry_norm',
            # 'dist_t5_norm_above_t2_t5_norm',
            # 'dist_t5_norm_below_t2_t5_norm',
            # 'dist_t5_norm_above_t3_entry_norm',
            # 'dist_t5_norm_below_t3_entry_norm',
            # 'dist_t5_norm_above_t1_entry_norm',
            # 'dist_t5_norm_below_t1_entry_norm',
            # 'dist_t5_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_t5_norm_take100_point_norm',
            # 'dist_t5_norm_mid_dist_t2_t5_norm',
            # 'dist_t5_norm_mid_dist_t5_entry_norm',
            # 'dist_t5_norm_mid_dist_t1_entry_norm',
            # 'dist_entry_point_norm_at_1_norm',
            # 'dist_entry_point_norm_at_2_norm',
            # 'dist_entry_point_norm_at_2_lc_norm',
            # 'dist_entry_point_norm_at_3_norm',
            # 'dist_entry_point_norm_at_4_norm',
            # 'dist_entry_point_norm_at_5_norm',
            # 'dist_entry_point_norm_at_5_lc_norm',
            # 'dist_entry_point_norm_at_6_norm',
            # 'dist_entry_point_norm_at_6_lc_norm',
            # 'dist_entry_point_norm_enter_cp_norm',
            # 'dist_entry_point_norm_cp_enter_norm',
            # 'dist_entry_point_norm_t4_cp_norm',
            # 'dist_entry_point_norm_t3_cp_norm',
            # 'dist_entry_point_norm_t2_cp_norm',
            # 'dist_entry_point_norm_t1_cp_norm',
            # 'dist_entry_point_norm_above_t1_t2_norm',
            # 'dist_entry_point_norm_below_t1_t2_norm',
            # 'dist_entry_point_norm_above_t2_t3_norm',
            # 'dist_entry_point_norm_below_t2_t3_norm',
            # 'dist_entry_point_norm_above_t3_t4_norm',
            # 'dist_entry_point_norm_below_t3_t4_norm',
            # 'dist_entry_point_norm_above_t4_t5_norm',
            # 'dist_entry_point_norm_below_t4_t5_norm',
            # 'dist_entry_point_norm_above_t5_entry_norm',
            # 'dist_entry_point_norm_below_t5_entry_norm',
            # 'dist_entry_point_norm_above_t2_t5_norm',
            # 'dist_entry_point_norm_below_t2_t5_norm',
            # 'dist_entry_point_norm_above_t3_entry_norm',
            # 'dist_entry_point_norm_below_t3_entry_norm',
            # 'dist_entry_point_norm_above_t1_entry_norm',
            # 'dist_entry_point_norm_below_t1_entry_norm',
            # 'dist_entry_point_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_entry_point_norm_take100_point_norm',
            # 'dist_entry_point_norm_mid_dist_t2_t5_norm',
            # 'dist_entry_point_norm_mid_dist_t5_entry_norm',
            # 'dist_entry_point_norm_mid_dist_t1_entry_norm',
            # 'dist_at_1_norm_at_2_norm',
            # 'dist_at_1_norm_at_2_lc_norm',
            # 'dist_at_1_norm_at_3_norm',
            # 'dist_at_1_norm_at_4_norm',
            # 'dist_at_1_norm_at_5_norm',
            # 'dist_at_1_norm_at_5_lc_norm',
            # 'dist_at_1_norm_at_6_norm',
            # 'dist_at_1_norm_at_6_lc_norm',
            # 'dist_at_1_norm_enter_cp_norm',
            # 'dist_at_1_norm_cp_enter_norm',
            # 'dist_at_1_norm_t4_cp_norm',
            # 'dist_at_1_norm_t3_cp_norm',
            # 'dist_at_1_norm_t2_cp_norm',
            # 'dist_at_1_norm_t1_cp_norm',
            # 'dist_at_1_norm_above_t1_t2_norm',
            # 'dist_at_1_norm_below_t1_t2_norm',
            # 'dist_at_1_norm_above_t2_t3_norm',
            # 'dist_at_1_norm_below_t2_t3_norm',
            # 'dist_at_1_norm_above_t3_t4_norm',
            # 'dist_at_1_norm_below_t3_t4_norm',
            # 'dist_at_1_norm_above_t4_t5_norm',
            # 'dist_at_1_norm_below_t4_t5_norm',
            # 'dist_at_1_norm_above_t5_entry_norm',
            # 'dist_at_1_norm_below_t5_entry_norm',
            # 'dist_at_1_norm_above_t2_t5_norm',
            # 'dist_at_1_norm_below_t2_t5_norm',
            # 'dist_at_1_norm_above_t3_entry_norm',
            # 'dist_at_1_norm_below_t3_entry_norm',
            # 'dist_at_1_norm_above_t1_entry_norm',
            # 'dist_at_1_norm_below_t1_entry_norm',
            # 'dist_at_1_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_at_1_norm_take100_point_norm',
            # 'dist_at_1_norm_mid_dist_t2_t5_norm',
            # 'dist_at_1_norm_mid_dist_t5_entry_norm',
            # 'dist_at_1_norm_mid_dist_t1_entry_norm',
            # 'dist_at_2_norm_at_2_lc_norm',
            # 'dist_at_2_norm_at_3_norm',
            # 'dist_at_2_norm_at_4_norm',
            # 'dist_at_2_norm_at_5_norm',
            # 'dist_at_2_norm_at_5_lc_norm',
            # 'dist_at_2_norm_at_6_norm',
            # 'dist_at_2_norm_at_6_lc_norm',
            # 'dist_at_2_norm_enter_cp_norm',
            # 'dist_at_2_norm_cp_enter_norm',
            # 'dist_at_2_norm_t4_cp_norm',
            # 'dist_at_2_norm_t3_cp_norm',
            # 'dist_at_2_norm_t2_cp_norm',
            # 'dist_at_2_norm_t1_cp_norm',
            # 'dist_at_2_norm_above_t1_t2_norm',
            # 'dist_at_2_norm_below_t1_t2_norm',
            # 'dist_at_2_norm_above_t2_t3_norm',
            # 'dist_at_2_norm_below_t2_t3_norm',
            # 'dist_at_2_norm_above_t3_t4_norm',
            # 'dist_at_2_norm_below_t3_t4_norm',
            # 'dist_at_2_norm_above_t4_t5_norm',
            # 'dist_at_2_norm_below_t4_t5_norm',
            # 'dist_at_2_norm_above_t5_entry_norm',
            # 'dist_at_2_norm_below_t5_entry_norm',
            # 'dist_at_2_norm_above_t2_t5_norm',
            # 'dist_at_2_norm_below_t2_t5_norm',
            # 'dist_at_2_norm_above_t3_entry_norm',
            # 'dist_at_2_norm_below_t3_entry_norm',
            # 'dist_at_2_norm_above_t1_entry_norm',
            # 'dist_at_2_norm_below_t1_entry_norm',
            # 'dist_at_2_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_at_2_norm_take100_point_norm',
            # 'dist_at_2_norm_mid_dist_t2_t5_norm',
            # 'dist_at_2_norm_mid_dist_t5_entry_norm',
            # 'dist_at_2_norm_mid_dist_t1_entry_norm',
            # 'dist_at_2_lc_norm_at_3_norm',
            # 'dist_at_2_lc_norm_at_4_norm',
            # 'dist_at_2_lc_norm_at_5_norm',
            # 'dist_at_2_lc_norm_at_5_lc_norm',
            # 'dist_at_2_lc_norm_at_6_norm',
            # 'dist_at_2_lc_norm_at_6_lc_norm',
            # 'dist_at_2_lc_norm_enter_cp_norm',
            # 'dist_at_2_lc_norm_cp_enter_norm',
            # 'dist_at_2_lc_norm_t4_cp_norm',
            # 'dist_at_2_lc_norm_t3_cp_norm',
            # 'dist_at_2_lc_norm_t2_cp_norm',
            # 'dist_at_2_lc_norm_t1_cp_norm',
            # 'dist_at_2_lc_norm_above_t1_t2_norm',
            # 'dist_at_2_lc_norm_below_t1_t2_norm',
            # 'dist_at_2_lc_norm_above_t2_t3_norm',
            # 'dist_at_2_lc_norm_below_t2_t3_norm',
            # 'dist_at_2_lc_norm_above_t3_t4_norm',
            # 'dist_at_2_lc_norm_below_t3_t4_norm',
            # 'dist_at_2_lc_norm_above_t4_t5_norm',
            # 'dist_at_2_lc_norm_below_t4_t5_norm',
            # 'dist_at_2_lc_norm_above_t5_entry_norm',
            # 'dist_at_2_lc_norm_below_t5_entry_norm',
            # 'dist_at_2_lc_norm_above_t2_t5_norm',
            # 'dist_at_2_lc_norm_below_t2_t5_norm',
            # 'dist_at_2_lc_norm_above_t3_entry_norm',
            # 'dist_at_2_lc_norm_below_t3_entry_norm',
            # 'dist_at_2_lc_norm_above_t1_entry_norm',
            # 'dist_at_2_lc_norm_below_t1_entry_norm',
            # 'dist_at_2_lc_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_at_2_lc_norm_take100_point_norm',
            # 'dist_at_2_lc_norm_mid_dist_t2_t5_norm',
            # 'dist_at_2_lc_norm_mid_dist_t5_entry_norm',
            # 'dist_at_2_lc_norm_mid_dist_t1_entry_norm',
            # 'dist_at_3_norm_at_4_norm',
            # 'dist_at_3_norm_at_5_norm',
            # 'dist_at_3_norm_at_5_lc_norm',
            # 'dist_at_3_norm_at_6_norm',
            # 'dist_at_3_norm_at_6_lc_norm',
            # 'dist_at_3_norm_enter_cp_norm',
            # 'dist_at_3_norm_cp_enter_norm',
            # 'dist_at_3_norm_t4_cp_norm',
            # 'dist_at_3_norm_t3_cp_norm',
            # 'dist_at_3_norm_t2_cp_norm',
            # 'dist_at_3_norm_t1_cp_norm',
            # 'dist_at_3_norm_above_t1_t2_norm',
            # 'dist_at_3_norm_below_t1_t2_norm',
            # 'dist_at_3_norm_above_t2_t3_norm',
            # 'dist_at_3_norm_below_t2_t3_norm',
            # 'dist_at_3_norm_above_t3_t4_norm',
            # 'dist_at_3_norm_below_t3_t4_norm',
            # 'dist_at_3_norm_above_t4_t5_norm',
            # 'dist_at_3_norm_below_t4_t5_norm',
            # 'dist_at_3_norm_above_t5_entry_norm',
            # 'dist_at_3_norm_below_t5_entry_norm',
            # 'dist_at_3_norm_above_t2_t5_norm',
            # 'dist_at_3_norm_below_t2_t5_norm',
            # 'dist_at_3_norm_above_t3_entry_norm',
            # 'dist_at_3_norm_below_t3_entry_norm',
            # 'dist_at_3_norm_above_t1_entry_norm',
            # 'dist_at_3_norm_below_t1_entry_norm',
            # 'dist_at_3_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_at_3_norm_take100_point_norm',
            # 'dist_at_3_norm_mid_dist_t2_t5_norm',
            # 'dist_at_3_norm_mid_dist_t5_entry_norm',
            # 'dist_at_3_norm_mid_dist_t1_entry_norm',
            # 'dist_at_4_norm_at_5_norm',
            # 'dist_at_4_norm_at_5_lc_norm',
            # 'dist_at_4_norm_at_6_norm',
            # 'dist_at_4_norm_at_6_lc_norm',
            # 'dist_at_4_norm_enter_cp_norm',
            # 'dist_at_4_norm_cp_enter_norm',
            # 'dist_at_4_norm_t4_cp_norm',
            # 'dist_at_4_norm_t3_cp_norm',
            # 'dist_at_4_norm_t2_cp_norm',
            # 'dist_at_4_norm_t1_cp_norm',
            # 'dist_at_4_norm_above_t1_t2_norm',
            # 'dist_at_4_norm_below_t1_t2_norm',
            # 'dist_at_4_norm_above_t2_t3_norm',
            # 'dist_at_4_norm_below_t2_t3_norm',
            # 'dist_at_4_norm_above_t3_t4_norm',
            # 'dist_at_4_norm_below_t3_t4_norm',
            # 'dist_at_4_norm_above_t4_t5_norm',
            # 'dist_at_4_norm_below_t4_t5_norm',
            # 'dist_at_4_norm_above_t5_entry_norm',
            # 'dist_at_4_norm_below_t5_entry_norm',
            # 'dist_at_4_norm_above_t2_t5_norm',
            # 'dist_at_4_norm_below_t2_t5_norm',
            # 'dist_at_4_norm_above_t3_entry_norm',
            # 'dist_at_4_norm_below_t3_entry_norm',
            # 'dist_at_4_norm_above_t1_entry_norm',
            # 'dist_at_4_norm_below_t1_entry_norm',
            # 'dist_at_4_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_at_4_norm_take100_point_norm',
            # 'dist_at_4_norm_mid_dist_t2_t5_norm',
            # 'dist_at_4_norm_mid_dist_t5_entry_norm',
            # 'dist_at_4_norm_mid_dist_t1_entry_norm',
            # 'dist_at_5_norm_at_5_lc_norm',
            # 'dist_at_5_norm_at_6_norm',
            # 'dist_at_5_norm_at_6_lc_norm',
            # 'dist_at_5_norm_enter_cp_norm',
            # 'dist_at_5_norm_cp_enter_norm',
            # 'dist_at_5_norm_t4_cp_norm',
            # 'dist_at_5_norm_t3_cp_norm',
            # 'dist_at_5_norm_t2_cp_norm',
            # 'dist_at_5_norm_t1_cp_norm',
            # 'dist_at_5_norm_above_t1_t2_norm',
            # 'dist_at_5_norm_below_t1_t2_norm',
            # 'dist_at_5_norm_above_t2_t3_norm',
            # 'dist_at_5_norm_below_t2_t3_norm',
            # 'dist_at_5_norm_above_t3_t4_norm',
            # 'dist_at_5_norm_below_t3_t4_norm',
            # 'dist_at_5_norm_above_t4_t5_norm',
            # 'dist_at_5_norm_below_t4_t5_norm',
            # 'dist_at_5_norm_above_t5_entry_norm',
            # 'dist_at_5_norm_below_t5_entry_norm',
            # 'dist_at_5_norm_above_t2_t5_norm',
            # 'dist_at_5_norm_below_t2_t5_norm',
            # 'dist_at_5_norm_above_t3_entry_norm',
            # 'dist_at_5_norm_below_t3_entry_norm',
            # 'dist_at_5_norm_above_t1_entry_norm',
            # 'dist_at_5_norm_below_t1_entry_norm',
            # 'dist_at_5_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_at_5_norm_take100_point_norm',
            # 'dist_at_5_norm_mid_dist_t2_t5_norm',
            # 'dist_at_5_norm_mid_dist_t5_entry_norm',
            # 'dist_at_5_norm_mid_dist_t1_entry_norm',
            # 'dist_at_5_lc_norm_at_6_norm',
            # 'dist_at_5_lc_norm_at_6_lc_norm',
            # 'dist_at_5_lc_norm_enter_cp_norm',
            # 'dist_at_5_lc_norm_cp_enter_norm',
            # 'dist_at_5_lc_norm_t4_cp_norm',
            # 'dist_at_5_lc_norm_t3_cp_norm',
            # 'dist_at_5_lc_norm_t2_cp_norm',
            # 'dist_at_5_lc_norm_t1_cp_norm',
            # 'dist_at_5_lc_norm_above_t1_t2_norm',
            # 'dist_at_5_lc_norm_below_t1_t2_norm',
            # 'dist_at_5_lc_norm_above_t2_t3_norm',
            # 'dist_at_5_lc_norm_below_t2_t3_norm',
            # 'dist_at_5_lc_norm_above_t3_t4_norm',
            # 'dist_at_5_lc_norm_below_t3_t4_norm',
            # 'dist_at_5_lc_norm_above_t4_t5_norm',
            # 'dist_at_5_lc_norm_below_t4_t5_norm',
            # 'dist_at_5_lc_norm_above_t5_entry_norm',
            # 'dist_at_5_lc_norm_below_t5_entry_norm',
            # 'dist_at_5_lc_norm_above_t2_t5_norm',
            # 'dist_at_5_lc_norm_below_t2_t5_norm',
            # 'dist_at_5_lc_norm_above_t3_entry_norm',
            # 'dist_at_5_lc_norm_below_t3_entry_norm',
            # 'dist_at_5_lc_norm_above_t1_entry_norm',
            # 'dist_at_5_lc_norm_below_t1_entry_norm',
            # 'dist_at_5_lc_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_at_5_lc_norm_take100_point_norm',
            # 'dist_at_5_lc_norm_mid_dist_t2_t5_norm',
            # 'dist_at_5_lc_norm_mid_dist_t5_entry_norm',
            # 'dist_at_5_lc_norm_mid_dist_t1_entry_norm',
            # 'dist_at_6_norm_at_6_lc_norm',
            # 'dist_at_6_norm_enter_cp_norm',
            # 'dist_at_6_norm_cp_enter_norm',
            # 'dist_at_6_norm_t4_cp_norm',
            # 'dist_at_6_norm_t3_cp_norm',
            # 'dist_at_6_norm_t2_cp_norm',
            # 'dist_at_6_norm_t1_cp_norm',
            # 'dist_at_6_norm_above_t1_t2_norm',
            # 'dist_at_6_norm_below_t1_t2_norm',
            # 'dist_at_6_norm_above_t2_t3_norm',
            # 'dist_at_6_norm_below_t2_t3_norm',
            # 'dist_at_6_norm_above_t3_t4_norm',
            # 'dist_at_6_norm_below_t3_t4_norm',
            # 'dist_at_6_norm_above_t4_t5_norm',
            # 'dist_at_6_norm_below_t4_t5_norm',
            # 'dist_at_6_norm_above_t5_entry_norm',
            # 'dist_at_6_norm_below_t5_entry_norm',
            # 'dist_at_6_norm_above_t2_t5_norm',
            # 'dist_at_6_norm_below_t2_t5_norm',
            # 'dist_at_6_norm_above_t3_entry_norm',
            # 'dist_at_6_norm_below_t3_entry_norm',
            # 'dist_at_6_norm_above_t1_entry_norm',
            # 'dist_at_6_norm_below_t1_entry_norm',
            # 'dist_at_6_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_at_6_norm_take100_point_norm',
            # 'dist_at_6_norm_mid_dist_t2_t5_norm',
            # 'dist_at_6_norm_mid_dist_t5_entry_norm',
            # 'dist_at_6_norm_mid_dist_t1_entry_norm',
            # 'dist_at_6_lc_norm_enter_cp_norm',
            # 'dist_at_6_lc_norm_cp_enter_norm',
            # 'dist_at_6_lc_norm_t4_cp_norm',
            # 'dist_at_6_lc_norm_t3_cp_norm',
            # 'dist_at_6_lc_norm_t2_cp_norm',
            # 'dist_at_6_lc_norm_t1_cp_norm',
            # 'dist_at_6_lc_norm_above_t1_t2_norm',
            # 'dist_at_6_lc_norm_below_t1_t2_norm',
            # 'dist_at_6_lc_norm_above_t2_t3_norm',
            # 'dist_at_6_lc_norm_below_t2_t3_norm',
            # 'dist_at_6_lc_norm_above_t3_t4_norm',
            # 'dist_at_6_lc_norm_below_t3_t4_norm',
            # 'dist_at_6_lc_norm_above_t4_t5_norm',
            # 'dist_at_6_lc_norm_below_t4_t5_norm',
            # 'dist_at_6_lc_norm_above_t5_entry_norm',
            # 'dist_at_6_lc_norm_below_t5_entry_norm',
            # 'dist_at_6_lc_norm_above_t2_t5_norm',
            # 'dist_at_6_lc_norm_below_t2_t5_norm',
            # 'dist_at_6_lc_norm_above_t3_entry_norm',
            # 'dist_at_6_lc_norm_below_t3_entry_norm',
            # 'dist_at_6_lc_norm_above_t1_entry_norm',
            # 'dist_at_6_lc_norm_below_t1_entry_norm',
            # 'dist_at_6_lc_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_at_6_lc_norm_take100_point_norm',
            # 'dist_at_6_lc_norm_mid_dist_t2_t5_norm',
            # 'dist_at_6_lc_norm_mid_dist_t5_entry_norm',
            # 'dist_at_6_lc_norm_mid_dist_t1_entry_norm',
            # 'dist_enter_cp_norm_cp_enter_norm',
            # 'dist_enter_cp_norm_t4_cp_norm',
            # 'dist_enter_cp_norm_t3_cp_norm',
            # 'dist_enter_cp_norm_t2_cp_norm',
            # 'dist_enter_cp_norm_t1_cp_norm',
            # 'dist_enter_cp_norm_above_t1_t2_norm',
            # 'dist_enter_cp_norm_below_t1_t2_norm',
            # 'dist_enter_cp_norm_above_t2_t3_norm',
            # 'dist_enter_cp_norm_below_t2_t3_norm',
            # 'dist_enter_cp_norm_above_t3_t4_norm',
            # 'dist_enter_cp_norm_below_t3_t4_norm',
            # 'dist_enter_cp_norm_above_t4_t5_norm',
            # 'dist_enter_cp_norm_below_t4_t5_norm',
            # 'dist_enter_cp_norm_above_t5_entry_norm',
            # 'dist_enter_cp_norm_below_t5_entry_norm',
            # 'dist_enter_cp_norm_above_t2_t5_norm',
            # 'dist_enter_cp_norm_below_t2_t5_norm',
            # 'dist_enter_cp_norm_above_t3_entry_norm',
            # 'dist_enter_cp_norm_below_t3_entry_norm',
            # 'dist_enter_cp_norm_above_t1_entry_norm',
            # 'dist_enter_cp_norm_below_t1_entry_norm',
            # 'dist_enter_cp_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_enter_cp_norm_take100_point_norm',
            # 'dist_enter_cp_norm_mid_dist_t2_t5_norm',
            # 'dist_enter_cp_norm_mid_dist_t5_entry_norm',
            # 'dist_enter_cp_norm_mid_dist_t1_entry_norm',
            # 'dist_cp_enter_norm_t4_cp_norm',
            # 'dist_cp_enter_norm_t3_cp_norm',
            # 'dist_cp_enter_norm_t2_cp_norm',
            # 'dist_cp_enter_norm_t1_cp_norm',
            # 'dist_cp_enter_norm_above_t1_t2_norm',
            # 'dist_cp_enter_norm_below_t1_t2_norm',
            # 'dist_cp_enter_norm_above_t2_t3_norm',
            # 'dist_cp_enter_norm_below_t2_t3_norm',
            # 'dist_cp_enter_norm_above_t3_t4_norm',
            # 'dist_cp_enter_norm_below_t3_t4_norm',
            # 'dist_cp_enter_norm_above_t4_t5_norm',
            # 'dist_cp_enter_norm_below_t4_t5_norm',
            # 'dist_cp_enter_norm_above_t5_entry_norm',
            # 'dist_cp_enter_norm_below_t5_entry_norm',
            # 'dist_cp_enter_norm_above_t2_t5_norm',
            # 'dist_cp_enter_norm_below_t2_t5_norm',
            # 'dist_cp_enter_norm_above_t3_entry_norm',
            # 'dist_cp_enter_norm_below_t3_entry_norm',
            # 'dist_cp_enter_norm_above_t1_entry_norm',
            # 'dist_cp_enter_norm_below_t1_entry_norm',
            # 'dist_cp_enter_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_cp_enter_norm_take100_point_norm',
            # 'dist_cp_enter_norm_mid_dist_t2_t5_norm',
            # 'dist_cp_enter_norm_mid_dist_t5_entry_norm',
            # 'dist_cp_enter_norm_mid_dist_t1_entry_norm',
            # 'dist_t4_cp_norm_t3_cp_norm',
            # 'dist_t4_cp_norm_t2_cp_norm',
            # 'dist_t4_cp_norm_t1_cp_norm',
            # 'dist_t4_cp_norm_above_t1_t2_norm',
            # 'dist_t4_cp_norm_below_t1_t2_norm',
            # 'dist_t4_cp_norm_above_t2_t3_norm',
            # 'dist_t4_cp_norm_below_t2_t3_norm',
            # 'dist_t4_cp_norm_above_t3_t4_norm',
            # 'dist_t4_cp_norm_below_t3_t4_norm',
            # 'dist_t4_cp_norm_above_t4_t5_norm',
            # 'dist_t4_cp_norm_below_t4_t5_norm',
            # 'dist_t4_cp_norm_above_t5_entry_norm',
            # 'dist_t4_cp_norm_below_t5_entry_norm',
            # 'dist_t4_cp_norm_above_t2_t5_norm',
            # 'dist_t4_cp_norm_below_t2_t5_norm',
            # 'dist_t4_cp_norm_above_t3_entry_norm',
            # 'dist_t4_cp_norm_below_t3_entry_norm',
            # 'dist_t4_cp_norm_above_t1_entry_norm',
            # 'dist_t4_cp_norm_below_t1_entry_norm',
            # 'dist_t4_cp_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_t4_cp_norm_take100_point_norm',
            # 'dist_t4_cp_norm_mid_dist_t2_t5_norm',
            # 'dist_t4_cp_norm_mid_dist_t5_entry_norm',
            # 'dist_t4_cp_norm_mid_dist_t1_entry_norm',
            # 'dist_t3_cp_norm_t2_cp_norm',
            # 'dist_t3_cp_norm_t1_cp_norm',
            # 'dist_t3_cp_norm_above_t1_t2_norm',
            # 'dist_t3_cp_norm_below_t1_t2_norm',
            # 'dist_t3_cp_norm_above_t2_t3_norm',
            # 'dist_t3_cp_norm_below_t2_t3_norm',
            # 'dist_t3_cp_norm_above_t3_t4_norm',
            # 'dist_t3_cp_norm_below_t3_t4_norm',
            # 'dist_t3_cp_norm_above_t4_t5_norm',
            # 'dist_t3_cp_norm_below_t4_t5_norm',
            # 'dist_t3_cp_norm_above_t5_entry_norm',
            # 'dist_t3_cp_norm_below_t5_entry_norm',
            # 'dist_t3_cp_norm_above_t2_t5_norm',
            # 'dist_t3_cp_norm_below_t2_t5_norm',
            # 'dist_t3_cp_norm_above_t3_entry_norm',
            # 'dist_t3_cp_norm_below_t3_entry_norm',
            # 'dist_t3_cp_norm_above_t1_entry_norm',
            # 'dist_t3_cp_norm_below_t1_entry_norm',
            # 'dist_t3_cp_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_t3_cp_norm_take100_point_norm',
            # 'dist_t3_cp_norm_mid_dist_t2_t5_norm',
            # 'dist_t3_cp_norm_mid_dist_t5_entry_norm',
            # 'dist_t3_cp_norm_mid_dist_t1_entry_norm',
            # 'dist_t2_cp_norm_t1_cp_norm',
            # 'dist_t2_cp_norm_above_t1_t2_norm',
            # 'dist_t2_cp_norm_below_t1_t2_norm',
            # 'dist_t2_cp_norm_above_t2_t3_norm',
            # 'dist_t2_cp_norm_below_t2_t3_norm',
            # 'dist_t2_cp_norm_above_t3_t4_norm',
            # 'dist_t2_cp_norm_below_t3_t4_norm',
            # 'dist_t2_cp_norm_above_t4_t5_norm',
            # 'dist_t2_cp_norm_below_t4_t5_norm',
            # 'dist_t2_cp_norm_above_t5_entry_norm',
            # 'dist_t2_cp_norm_below_t5_entry_norm',
            # 'dist_t2_cp_norm_above_t2_t5_norm',
            # 'dist_t2_cp_norm_below_t2_t5_norm',
            # 'dist_t2_cp_norm_above_t3_entry_norm',
            # 'dist_t2_cp_norm_below_t3_entry_norm',
            # 'dist_t2_cp_norm_above_t1_entry_norm',
            # 'dist_t2_cp_norm_below_t1_entry_norm',
            # 'dist_t2_cp_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_t2_cp_norm_take100_point_norm',
            # 'dist_t2_cp_norm_mid_dist_t2_t5_norm',
            # 'dist_t2_cp_norm_mid_dist_t5_entry_norm',
            # 'dist_t2_cp_norm_mid_dist_t1_entry_norm',
            # 'dist_t1_cp_norm_above_t1_t2_norm',
            # 'dist_t1_cp_norm_below_t1_t2_norm',
            # 'dist_t1_cp_norm_above_t2_t3_norm',
            # 'dist_t1_cp_norm_below_t2_t3_norm',
            # 'dist_t1_cp_norm_above_t3_t4_norm',
            # 'dist_t1_cp_norm_below_t3_t4_norm',
            # 'dist_t1_cp_norm_above_t4_t5_norm',
            # 'dist_t1_cp_norm_below_t4_t5_norm',
            # 'dist_t1_cp_norm_above_t5_entry_norm',
            # 'dist_t1_cp_norm_below_t5_entry_norm',
            # 'dist_t1_cp_norm_above_t2_t5_norm',
            # 'dist_t1_cp_norm_below_t2_t5_norm',
            # 'dist_t1_cp_norm_above_t3_entry_norm',
            # 'dist_t1_cp_norm_below_t3_entry_norm',
            # 'dist_t1_cp_norm_above_t1_entry_norm',
            # 'dist_t1_cp_norm_below_t1_entry_norm',
            # 'dist_t1_cp_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_t1_cp_norm_take100_point_norm',
            # 'dist_t1_cp_norm_mid_dist_t2_t5_norm',
            # 'dist_t1_cp_norm_mid_dist_t5_entry_norm',
            # 'dist_t1_cp_norm_mid_dist_t1_entry_norm',
            # 'dist_above_t1_t2_norm_below_t1_t2_norm',
            # 'dist_above_t1_t2_norm_above_t2_t3_norm',
            # 'dist_above_t1_t2_norm_below_t2_t3_norm',
            # 'dist_above_t1_t2_norm_above_t3_t4_norm',
            # 'dist_above_t1_t2_norm_below_t3_t4_norm',
            # 'dist_above_t1_t2_norm_above_t4_t5_norm',
            # 'dist_above_t1_t2_norm_below_t4_t5_norm',
            # 'dist_above_t1_t2_norm_above_t5_entry_norm',
            # 'dist_above_t1_t2_norm_below_t5_entry_norm',
            # 'dist_above_t1_t2_norm_above_t2_t5_norm',
            # 'dist_above_t1_t2_norm_below_t2_t5_norm',
            # 'dist_above_t1_t2_norm_above_t3_entry_norm',
            # 'dist_above_t1_t2_norm_below_t3_entry_norm',
            # 'dist_above_t1_t2_norm_above_t1_entry_norm',
            # 'dist_above_t1_t2_norm_below_t1_entry_norm',
            # 'dist_above_t1_t2_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_above_t1_t2_norm_take100_point_norm',
            # 'dist_above_t1_t2_norm_mid_dist_t2_t5_norm',
            # 'dist_above_t1_t2_norm_mid_dist_t5_entry_norm',
            # 'dist_above_t1_t2_norm_mid_dist_t1_entry_norm',
            # 'dist_below_t1_t2_norm_above_t2_t3_norm',
            # 'dist_below_t1_t2_norm_below_t2_t3_norm',
            # 'dist_below_t1_t2_norm_above_t3_t4_norm',
            # 'dist_below_t1_t2_norm_below_t3_t4_norm',
            # 'dist_below_t1_t2_norm_above_t4_t5_norm',
            # 'dist_below_t1_t2_norm_below_t4_t5_norm',
            # 'dist_below_t1_t2_norm_above_t5_entry_norm',
            # 'dist_below_t1_t2_norm_below_t5_entry_norm',
            # 'dist_below_t1_t2_norm_above_t2_t5_norm',
            # 'dist_below_t1_t2_norm_below_t2_t5_norm',
            # 'dist_below_t1_t2_norm_above_t3_entry_norm',
            # 'dist_below_t1_t2_norm_below_t3_entry_norm',
            # 'dist_below_t1_t2_norm_above_t1_entry_norm',
            # 'dist_below_t1_t2_norm_below_t1_entry_norm',
            # 'dist_below_t1_t2_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_below_t1_t2_norm_take100_point_norm',
            # 'dist_below_t1_t2_norm_mid_dist_t2_t5_norm',
            # 'dist_below_t1_t2_norm_mid_dist_t5_entry_norm',
            # 'dist_below_t1_t2_norm_mid_dist_t1_entry_norm',
            # 'dist_above_t2_t3_norm_below_t2_t3_norm',
            # 'dist_above_t2_t3_norm_above_t3_t4_norm',
            # 'dist_above_t2_t3_norm_below_t3_t4_norm',
            # 'dist_above_t2_t3_norm_above_t4_t5_norm',
            # 'dist_above_t2_t3_norm_below_t4_t5_norm',
            # 'dist_above_t2_t3_norm_above_t5_entry_norm',
            # 'dist_above_t2_t3_norm_below_t5_entry_norm',
            # 'dist_above_t2_t3_norm_above_t2_t5_norm',
            # 'dist_above_t2_t3_norm_below_t2_t5_norm',
            # 'dist_above_t2_t3_norm_above_t3_entry_norm',
            # 'dist_above_t2_t3_norm_below_t3_entry_norm',
            # 'dist_above_t2_t3_norm_above_t1_entry_norm',
            # 'dist_above_t2_t3_norm_below_t1_entry_norm',
            # 'dist_above_t2_t3_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_above_t2_t3_norm_take100_point_norm',
            # 'dist_above_t2_t3_norm_mid_dist_t2_t5_norm',
            # 'dist_above_t2_t3_norm_mid_dist_t5_entry_norm',
            # 'dist_above_t2_t3_norm_mid_dist_t1_entry_norm',
            # 'dist_below_t2_t3_norm_above_t3_t4_norm',
            # 'dist_below_t2_t3_norm_below_t3_t4_norm',
            # 'dist_below_t2_t3_norm_above_t4_t5_norm',
            # 'dist_below_t2_t3_norm_below_t4_t5_norm',
            # 'dist_below_t2_t3_norm_above_t5_entry_norm',
            # 'dist_below_t2_t3_norm_below_t5_entry_norm',
            # 'dist_below_t2_t3_norm_above_t2_t5_norm',
            # 'dist_below_t2_t3_norm_below_t2_t5_norm',
            # 'dist_below_t2_t3_norm_above_t3_entry_norm',
            # 'dist_below_t2_t3_norm_below_t3_entry_norm',
            # 'dist_below_t2_t3_norm_above_t1_entry_norm',
            # 'dist_below_t2_t3_norm_below_t1_entry_norm',
            # 'dist_below_t2_t3_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_below_t2_t3_norm_take100_point_norm',
            # 'dist_below_t2_t3_norm_mid_dist_t2_t5_norm',
            # 'dist_below_t2_t3_norm_mid_dist_t5_entry_norm',
            # 'dist_below_t2_t3_norm_mid_dist_t1_entry_norm',
            # 'dist_above_t3_t4_norm_below_t3_t4_norm',
            # 'dist_above_t3_t4_norm_above_t4_t5_norm',
            # 'dist_above_t3_t4_norm_below_t4_t5_norm',
            # 'dist_above_t3_t4_norm_above_t5_entry_norm',
            # 'dist_above_t3_t4_norm_below_t5_entry_norm',
            # 'dist_above_t3_t4_norm_above_t2_t5_norm',
            # 'dist_above_t3_t4_norm_below_t2_t5_norm',
            # 'dist_above_t3_t4_norm_above_t3_entry_norm',
            # 'dist_above_t3_t4_norm_below_t3_entry_norm',
            # 'dist_above_t3_t4_norm_above_t1_entry_norm',
            # 'dist_above_t3_t4_norm_below_t1_entry_norm',
            # 'dist_above_t3_t4_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_above_t3_t4_norm_take100_point_norm',
            # 'dist_above_t3_t4_norm_mid_dist_t2_t5_norm',
            # 'dist_above_t3_t4_norm_mid_dist_t5_entry_norm',
            # 'dist_above_t3_t4_norm_mid_dist_t1_entry_norm',
            # 'dist_below_t3_t4_norm_above_t4_t5_norm',
            # 'dist_below_t3_t4_norm_below_t4_t5_norm',
            # 'dist_below_t3_t4_norm_above_t5_entry_norm',
            # 'dist_below_t3_t4_norm_below_t5_entry_norm',
            # 'dist_below_t3_t4_norm_above_t2_t5_norm',
            # 'dist_below_t3_t4_norm_below_t2_t5_norm',
            # 'dist_below_t3_t4_norm_above_t3_entry_norm',
            # 'dist_below_t3_t4_norm_below_t3_entry_norm',
            # 'dist_below_t3_t4_norm_above_t1_entry_norm',
            # 'dist_below_t3_t4_norm_below_t1_entry_norm',
            # 'dist_below_t3_t4_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_below_t3_t4_norm_take100_point_norm',
            # 'dist_below_t3_t4_norm_mid_dist_t2_t5_norm',
            # 'dist_below_t3_t4_norm_mid_dist_t5_entry_norm',
            # 'dist_below_t3_t4_norm_mid_dist_t1_entry_norm',
            # 'dist_above_t4_t5_norm_below_t4_t5_norm',
            # 'dist_above_t4_t5_norm_above_t5_entry_norm',
            # 'dist_above_t4_t5_norm_below_t5_entry_norm',
            # 'dist_above_t4_t5_norm_above_t2_t5_norm',
            # 'dist_above_t4_t5_norm_below_t2_t5_norm',
            # 'dist_above_t4_t5_norm_above_t3_entry_norm',
            # 'dist_above_t4_t5_norm_below_t3_entry_norm',
            # 'dist_above_t4_t5_norm_above_t1_entry_norm',
            # 'dist_above_t4_t5_norm_below_t1_entry_norm',
            # 'dist_above_t4_t5_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_above_t4_t5_norm_take100_point_norm',
            # 'dist_above_t4_t5_norm_mid_dist_t2_t5_norm',
            # 'dist_above_t4_t5_norm_mid_dist_t5_entry_norm',
            # 'dist_above_t4_t5_norm_mid_dist_t1_entry_norm',
            # 'dist_below_t4_t5_norm_above_t5_entry_norm',
            # 'dist_below_t4_t5_norm_below_t5_entry_norm',
            # 'dist_below_t4_t5_norm_above_t2_t5_norm',
            # 'dist_below_t4_t5_norm_below_t2_t5_norm',
            # 'dist_below_t4_t5_norm_above_t3_entry_norm',
            # 'dist_below_t4_t5_norm_below_t3_entry_norm',
            # 'dist_below_t4_t5_norm_above_t1_entry_norm',
            # 'dist_below_t4_t5_norm_below_t1_entry_norm',
            # 'dist_below_t4_t5_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_below_t4_t5_norm_take100_point_norm',
            # 'dist_below_t4_t5_norm_mid_dist_t2_t5_norm',
            # 'dist_below_t4_t5_norm_mid_dist_t5_entry_norm',
            # 'dist_below_t4_t5_norm_mid_dist_t1_entry_norm',
            # 'dist_above_t5_entry_norm_below_t5_entry_norm',
            # 'dist_above_t5_entry_norm_above_t2_t5_norm',
            # 'dist_above_t5_entry_norm_below_t2_t5_norm',
            # 'dist_above_t5_entry_norm_above_t3_entry_norm',
            # 'dist_above_t5_entry_norm_below_t3_entry_norm',
            # 'dist_above_t5_entry_norm_above_t1_entry_norm',
            # 'dist_above_t5_entry_norm_below_t1_entry_norm',
            # 'dist_above_t5_entry_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_above_t5_entry_norm_take100_point_norm',
            # 'dist_above_t5_entry_norm_mid_dist_t2_t5_norm',
            # 'dist_above_t5_entry_norm_mid_dist_t5_entry_norm',
            # 'dist_above_t5_entry_norm_mid_dist_t1_entry_norm',
            # 'dist_below_t5_entry_norm_above_t2_t5_norm',
            # 'dist_below_t5_entry_norm_below_t2_t5_norm',
            # 'dist_below_t5_entry_norm_above_t3_entry_norm',
            # 'dist_below_t5_entry_norm_below_t3_entry_norm',
            # 'dist_below_t5_entry_norm_above_t1_entry_norm',
            # 'dist_below_t5_entry_norm_below_t1_entry_norm',
            # 'dist_below_t5_entry_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_below_t5_entry_norm_take100_point_norm',
            # 'dist_below_t5_entry_norm_mid_dist_t2_t5_norm',
            # 'dist_below_t5_entry_norm_mid_dist_t5_entry_norm',
            # 'dist_below_t5_entry_norm_mid_dist_t1_entry_norm',
            # 'dist_above_t2_t5_norm_below_t2_t5_norm',
            # 'dist_above_t2_t5_norm_above_t3_entry_norm',
            # 'dist_above_t2_t5_norm_below_t3_entry_norm',
            # 'dist_above_t2_t5_norm_above_t1_entry_norm',
            # 'dist_above_t2_t5_norm_below_t1_entry_norm',
            # 'dist_above_t2_t5_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_above_t2_t5_norm_take100_point_norm',
            # 'dist_above_t2_t5_norm_mid_dist_t2_t5_norm',
            # 'dist_above_t2_t5_norm_mid_dist_t5_entry_norm',
            # 'dist_above_t2_t5_norm_mid_dist_t1_entry_norm',
            # 'dist_below_t2_t5_norm_above_t3_entry_norm',
            # 'dist_below_t2_t5_norm_below_t3_entry_norm',
            # 'dist_below_t2_t5_norm_above_t1_entry_norm',
            # 'dist_below_t2_t5_norm_below_t1_entry_norm',
            # 'dist_below_t2_t5_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_below_t2_t5_norm_take100_point_norm',
            # 'dist_below_t2_t5_norm_mid_dist_t2_t5_norm',
            # 'dist_below_t2_t5_norm_mid_dist_t5_entry_norm',
            # 'dist_below_t2_t5_norm_mid_dist_t1_entry_norm',
            # 'dist_above_t3_entry_norm_below_t3_entry_norm',
            # 'dist_above_t3_entry_norm_above_t1_entry_norm',
            # 'dist_above_t3_entry_norm_below_t1_entry_norm',
            # 'dist_above_t3_entry_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_above_t3_entry_norm_take100_point_norm',
            # 'dist_above_t3_entry_norm_mid_dist_t2_t5_norm',
            # 'dist_above_t3_entry_norm_mid_dist_t5_entry_norm',
            # 'dist_above_t3_entry_norm_mid_dist_t1_entry_norm',
            # 'dist_below_t3_entry_norm_above_t1_entry_norm',
            # 'dist_below_t3_entry_norm_below_t1_entry_norm',
            # 'dist_below_t3_entry_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_below_t3_entry_norm_take100_point_norm',
            # 'dist_below_t3_entry_norm_mid_dist_t2_t5_norm',
            # 'dist_below_t3_entry_norm_mid_dist_t5_entry_norm',
            # 'dist_below_t3_entry_norm_mid_dist_t1_entry_norm',
            # 'dist_above_t1_entry_norm_below_t1_entry_norm',
            # 'dist_above_t1_entry_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_above_t1_entry_norm_take100_point_norm',
            # 'dist_above_t1_entry_norm_mid_dist_t2_t5_norm',
            # 'dist_above_t1_entry_norm_mid_dist_t5_entry_norm',
            # 'dist_above_t1_entry_norm_mid_dist_t1_entry_norm',
            # 'dist_below_t1_entry_norm_intersect_t3_t4_t2_t5_norm',
            # 'dist_below_t1_entry_norm_take100_point_norm',
            # 'dist_below_t1_entry_norm_mid_dist_t2_t5_norm',
            # 'dist_below_t1_entry_norm_mid_dist_t5_entry_norm',
            # 'dist_below_t1_entry_norm_mid_dist_t1_entry_norm',
            # 'dist_intersect_t3_t4_t2_t5_norm_take100_point_norm',
            # 'dist_intersect_t3_t4_t2_t5_norm_mid_dist_t2_t5_norm',
            # 'dist_intersect_t3_t4_t2_t5_norm_mid_dist_t5_entry_norm',
            # 'dist_intersect_t3_t4_t2_t5_norm_mid_dist_t1_entry_norm',
            # 'dist_take100_point_norm_mid_dist_t2_t5_norm',
            # 'dist_take100_point_norm_mid_dist_t5_entry_norm',
            # 'dist_take100_point_norm_mid_dist_t1_entry_norm',
            # 'dist_mid_dist_t2_t5_norm_mid_dist_t5_entry_norm',
            # 'dist_mid_dist_t2_t5_norm_mid_dist_t1_entry_norm',
            # 'dist_mid_dist_t5_entry_norm_mid_dist_t1_entry_norm'
            # 'skewness_open',
            # 'center_of_mass_with_CP[0]',
            # 'center_of_mass[1]',
            # 'euclidean_distance_center_of_mass_with_CP',
            # 'euclidean_distance_center_of_mass_without_weight',
            # 'component_1',
            # 'component_2',
            # 'component_3',
            # 'component_4',
            # 'mse_d2_t1_t4',
            # 'coeffs_d2_t1_t4',
            # 'mse_d3_t1_t4',
            # 'self.mse_d1_t1_t4',
            # 'skewness',
            # 'kurt',
            # 'skewness_open_close',
            # 'mse_d2_t2_t4',
            # 'mse_d1_t2_t4',
            # 'coeffs_d3_t2_t4',
            # 'mse_d1_t1_t3',
            # 'skewness_close',
            # 'derivative_at_x_t1_d4',
            # 'kurtosis_distribution',
            # 'force_close_minutes'
        ]

        wb = Workbook()
        ws = wb.active

        for col_num, header in enumerate(headers, start=1):
            col_letter = get_column_letter(col_num)
            ws[f'{col_letter}1'] = header

        for row_num, params in enumerate(self.all_other_parameters, start=2):
            for col_num, param in enumerate(params, start=1):
                col_letter = get_column_letter(col_num)
                ws[f'{col_letter}{row_num}'] = param

        self.adjust_column_width(ws)

        wb.save(file_path)
        wb.close()

    def save(self):
        """Сохранение файла."""
        result_path = self.get_file_path()
        self.write_to_excel(result_path)
